import { BettingcardProps } from '../components/bets/card/Bettingcard'

export const BettingData: Array<BettingcardProps> = [
  {
    id: '1',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '2',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '3',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '4',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '5',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '6',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '7',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
  {
    id: '8',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '9',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '10',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: '10.03.22',
    bettingVolume: '171',
  },
  {
    id: '11',
    series: 'Serie A',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '08.03.22',
    bettingDeadline: 'expired',
    bettingVolume: '171',
  },
]
