import { SquidCardProps } from '../components/squid/SquidCard'

export const SquidData: Array<SquidCardProps> = [
  {
    id: '1',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '21-11-22',
    bettingDeadline: '21-11-22',
    bettingVolume: '171',
    href: 'one',
    buttonText: 'Enter',
    sbc: 'Squid Bet Competition Week 1',
  },
  {
    id: '2',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '28-11-22',
    bettingDeadline: '28-11-22',
    bettingVolume: '171',
    href: 'two',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 2',
  },
  {
    id: '3',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '05-12-22',
    bettingDeadline: '05-12-22',
    bettingVolume: '171',
    href: 'three',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 3',
  },
  {
    id: '4',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '12-12-22',
    bettingDeadline: '12-12-22',
    bettingVolume: '171',
    href: 'four',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 4',
  },
  {
    id: '5',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Sampdoria',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '19-12-22',
    bettingDeadline: '19-12-22',
    bettingVolume: '171',
    href: 'five',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 5',
  },
  {
    id: '6',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '26-12-22',
    bettingDeadline: '26-12-22',
    bettingVolume: '171',
    href: 'six',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 6',
  },
  {
    id: '7',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '02-01-23',
    bettingDeadline: '02-01-23',
    bettingVolume: '171',
    href: 'seven',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 7',
  },
  {
    id: '8',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '09-01-23',
    bettingDeadline: '09-01-23',
    bettingVolume: '171',
    href: 'eight',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 8',
  },

  {
    id: '9',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '16-01-23',
    bettingDeadline: '16-01-23',
    bettingVolume: '171',
    href: 'nine',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 9',
  },
  {
    id: '10',
    series: 'SBC',
    team1: 'Atalanta',
    team2: 'Juventus',
    bettingType: 'football',
    bettingLogo: '/images/svgs/sidebar/soccer-ball.svg',
    bettingTime: '12:00',
    bettingDate: '23-01-23',
    bettingDeadline: '23-01-23',
    bettingVolume: '171',
    href: 'ten',
    buttonText: 'Register Now',
    sbc: 'Squid Bet Competition Week 10',
  },
]
